In [15]:
import pandas as pd

df = pd.read_csv("../data/framingham.csv")

df.head(5000)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [16]:
df.shape

(4240, 16)

In [17]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [18]:
df["TenYearCHD"].value_counts(normalize=True)

TenYearCHD
0    0.848113
1    0.151887
Name: proportion, dtype: float64

In [27]:
df["BPMeds"].value_counts(normalize=True)

BPMeds
0.0    0.970385
1.0    0.029615
Name: proportion, dtype: float64

In [19]:
(df.isna().mean()*100).sort_values(ascending=False).head(20)

glucose            9.150943
education          2.476415
BPMeds             1.250000
totChol            1.179245
cigsPerDay         0.683962
BMI                0.448113
heartRate          0.023585
male               0.000000
prevalentHyp       0.000000
prevalentStroke    0.000000
age                0.000000
currentSmoker      0.000000
diaBP              0.000000
sysBP              0.000000
diabetes           0.000000
TenYearCHD         0.000000
dtype: float64

In [20]:
df[["sysBP","diaBP"]].corr()

          sysBP     diaBP
sysBP  1.000000  0.783952
diaBP  0.783952  1.000000

In [21]:
features = [
    "age","male","currentSmoker","cigsPerDay",
    "diabetes","BMI","sysBP","totChol","glucose"
]

In [22]:
X = df[features]
y = df["TenYearCHD"]

In [25]:
X.head()

,age,male,currentSmoker,cigsPerDay,diabetes,BMI,sysBP,totChol,glucose
0,39,1,0,0.0,0,26.97,106.0,195.0,77.0
1,46,0,0,0.0,0,28.73,121.0,250.0,76.0
2,48,1,1,20.0,0,25.34,127.5,245.0,70.0
3,61,0,1,30.0,0,28.58,150.0,225.0,103.0
4,46,0,1,23.0,0,23.10,130.0,285.0,85.0

In [26]:
y.head()

0    0
1    0
2    0
3    1
4    0
Name: TenYearCHD, dtype: int64